### ISSUE TITLE
Probleme push 

### ISSUE THREAD

**Issue by OlivieriMaria-Louisa** [OlivieriMaria-Louisa/MariaLouisa-Olivieri-blog#1]
![72975738_535335650558911_4716537740764643328_n](https://user-images.githubusercontent.com/55577499/67505932-7331ab00-f68c-11e9-88b4-f8a09bdda085.jpg)
Voila mon soucis...

**Comment by OlivieriMaria-Louisa** [comment]
@GuyliannEngels

**Comment by GuyliannEngels** [comment]
Si tu ne me cites pas, je risquais pas de voir ta demande :p 

ferme tous tes documents, fais un commit, puis un PULL. 
tu as un conflit à gérer je pense

**Comment by OlivieriMaria-Louisa** [comment]
J'ai commit et pull dans Rstudio. Comment j'ai généré un conflit?

**Comment by GuyliannEngels** [comment]
Ha c'est la grande question ...

J'ai plusieurs hypothèses à te proposer 

- [ ] Tu n'es pas seule dans ta tête et tu as réalisé un conflit entre toi et toi. Dans ce cas, il faut peut être consulté :D 

- [ ] Tu as employé deux ordinateurs différents ? 

- [ ]  Tu as reclonné ton projet pour une raison qui m'échappe 

- [x] Aucune des trois réponses 

Choisis la bonne réponse

**Comment by OlivieriMaria-Louisa** [comment]
Je sais pas du tout ce que j'ai fais, a part essayer de crée un pdf de mon article 1

**Comment by GuyliannEngels** [comment]
pour le moment, je ne vois pas ton pdf sur ton blog 

tu peux t'inspirer de ce blog afin de trouver comment ajouter un pdf 

<https://guyliann.github.io/guyliann-engels-blog/>

**Comment by OlivieriMaria-Louisa** [comment]
Merci bcp!
